alias ls='ls --color=auto'
alias lla='ls -la'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fuck='sudo "$BASH" -c "$(history -p !!)"'
alias br-high='echo 250 | sudo tee /sys/class/backlight/*/brightness'
alias br-low='echo 30 | sudo tee /sys/class/backlight/*/brightness'
alias newvenv='python -m venv venv && source ./venv/bin/activate && pip install --upgrade pip'